### ISSUE TITLE
kali磁盘扩展

### ISSUE THREAD

**Issue by fightingman1** [nickmyb/android_security_zero_to_one#1]
大佬问一个问题，下载r0ysue大佬的kali种子之后，想要扩展磁盘空间。在网上的教程大部分是通过gaparts这个工具进行拓展的，但是因为没有iso文件，所以无法进入live模式，而命令行拓展磁盘空间，也无法整合到/dev/sda1上。所以想请问两个问题：一是如何在/dev/sda1上拓展磁盘空间；二是即使额外拓展了某个磁盘，例如/dev/sda3，那么编译AOSP源码是否没有问题

**Comment by nickmyb** [comment]
如果想要拓展原有的sda1可以网上搜教程，群里我记得有人成功过的但可能有风险，快照后操作即可，更建议直接拓展一块新盘例如sda3来放置源码，编译AOSP是完全可以的，我的文章的操作全是在sda3上操作的。如果还是有问题的话直接新建虚拟机按我的文章操作肯定可以成功（现在需要自行安装JDK8）或者直接下载我那个编译好AOSP的百G虚拟机镜像。反正凡事操作前快照或者新解压虚拟机重来即可。

**Comment by nickmyb** [comment]
> 大佬问一个问题，下载r0ysue大佬的kali种子之后，想要扩展磁盘空间。在网上的教程大部分是通过gaparts这个工具进行拓展的，但是因为没有iso文件，所以无法进入live模式，而命令行拓展磁盘空间，也无法整合到/dev/sda1上。所以想请问两个问题：一是如何在/dev/sda1上拓展磁盘空间；二是即使额外拓展了某个磁盘，例如/dev/sda3，那么编译AOSP源码是否没有问题

如果想要拓展原有的sda1可以网上搜教程，群里我记得有人成功过的但可能有风险，快照后操作即可，更建议直接拓展一块新盘例如sda3来放置源码，编译AOSP是完全可以的，我的文章的操作全是在sda3上操作的。如果还是有问题的话直接新建虚拟机按我的文章操作肯定可以成功（现在需要自行安装JDK8）或者直接下载我那个编译好AOSP的百G虚拟机镜像。反正凡事操作前快照或者新解压虚拟机重来即可。

**Comment by fightingman1** [comment]
> > 大佬问一个问题，下载r0ysue大佬的kali种子之后，想要扩展磁盘空间。在网上的教程大部分是通过gaparts这个工具进行拓展的，但是因为没有iso文件，所以无法进入live模式，而命令行拓展磁盘空间，也无法整合到/dev/sda1上。所以想请问两个问题：一是如何在/dev/sda1上拓展磁盘空间；二是即使额外拓展了某个磁盘，例如/dev/sda3，那么编译AOSP源码是否没有问题
> 
> 如果想要拓展原有的sda1可以网上搜教程，群里我记得有人成功过的但可能有风险，快照后操作即可，更建议直接拓展一块新盘例如sda3来放置源码，编译AOSP是完全可以的，我的文章的操作全是在sda3上操作的。如果还是有问题的话直接新建虚拟机按我的文章操作肯定可以成功（现在需要自行安装JDK8）或者直接下载我那个编译好AOSP的百G虚拟机镜像。反正凡事操作前快照或者新解压虚拟机重来即可。

嗯嗯
